export { default as navLogo } from '../assets/Image/logoAmen.svg'
export { default as navUz } from '../assets/Image/navUz.svg'
export { default as heroBackground } from '../assets/Image/hero/hero4.jpg'
export { default as teacher1 } from '../assets/Image/Teacher/teacher1.png'
export { default as teacher2 } from '../assets/Image/Teacher/teacher2.jpg'
export { default as Amplitude } from '../assets/Image/Partners/Amplitude.png'
export { default as Asana } from '../assets/Image/Partners/Asana.png'
export { default as Atlassian } from '../assets/Image/Partners/Atlassian.png'
export { default as Gitlab } from '../assets/Image/Partners/Gitlab.png'
export { default as Google } from '../assets/Image/Partners/Google.png'
export { default as Razorpay } from '../assets/Image/Partners/Razorpay.png'
export { default as Courses1 } from '../assets/Image/Courses/Hr1.png'
export { default as Courses2 } from '../assets/Image/Courses/Hr2.png'
export { default as freeCourses1 } from '../assets/Image/FreeCourses/freeCurs1.png'
export { default as freeCourses2 } from '../assets/Image/FreeCourses/freeCurs2.png'
export { default as freeCourses3 } from '../assets/Image/FreeCourses/freeCurs3.png'
export { default as freeCourses4 } from '../assets/Image/FreeCourses/freeCurs4.png'
export { default as image1 } from '../assets/Image/Feedback/image1.png'
export { default as image2 } from '../assets/Image/Feedback/image2.png'
export { default as image3 } from '../assets/Image/Feedback/image3.png'
export { default as image4 } from '../assets/Image/Feedback/image4.png'
export { default as image5 } from '../assets/Image/Feedback/image5.png'
export { default as image6 } from '../assets/Image/Feedback/image6.png'
export { default as googlePlay } from '../assets/Image/Download/GooglePlay.svg'
export { default as AppStory } from '../assets/Image/Download/AppStory.svg'
export { default as qrPhone } from '../assets/Image/Download/qrcod.svg'
export { default as footerLogo } from '../assets/Image/Footer/AmeenFooterLogo.svg'
export { default as RQ1 } from '../assets/Image/QrCourses/RQ1.png'
export { default as RQ2 } from '../assets/Image/QrCourses/RQ2.png'
export { default as RQ3 } from '../assets/Image/QrCourses/RQ3.png'
export { default as RQ4 } from '../assets/Image/QrCourses/RQ4.png'
export { default as vie1 } from '../assets/Image/CourseOverview/Vie1.png'
export { default as icon } from '../assets/Image/Icon.svg'
export { default as iconx } from '../assets/Image/Iconx.svg'
export { default as featuresImage } from '../assets/Image/Benefits/featuresImage.png'
export { default as benefitsLogo } from '../assets/Image/Benefits/benefitsLogo.svg'
export { default as playmini } from '../assets/playmini.svg'
export { default as failmini } from '../assets/failmini.svg'
export { default as instagram } from '../assets/Image/Footer/Instagram.svg'
export { default as telegram } from '../assets/Image/Footer/Telegram.svg'
export { default as youtube } from '../assets/Image/Footer/YouTube.svg'
export { default as facebook } from '../assets/Image/Footer/Facebook.svg'
export { default as PlayButton} from '../assets/PlayButton.svg'
export { default as Play} from '../assets/Image/play.svg'
export { default as nextBtn} from '../assets/nextBtn.svg'
export { default as prevBtn} from '../assets/prevBtn.svg'